---
title: "Skunks in British Columbia - Spatial Exploration"
author: "Shayla Tran, Matthew Angoh & Kyle Deng"
date: "2024-04-17"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Loading and cleaning the occurence data from GBIF

The dataset contains both Striped Skunk (Mephitis mephitis), which can be found throughout much of the province and the less common Western Spotted Skunk (Spilogale gracilis) which is found in the Lower Mainland.
```{r, message=FALSE}
library(tidyverse)
library(vroom)
library(spatstat)
library(sf)
library(polyCub)
library(rgbif)

load("BC_Covariates.Rda")
skunks <- vroom::vroom("0189800-240321170329656.csv", quote="") %>%
  filter(stateProvince == 'British Columbia') %>%
  select(species, locality, decimalLatitude, decimalLongitude) %>%
  drop_na(decimalLatitude, decimalLongitude)

skunks <- st_as_sf(skunks, coords = c("decimalLongitude", "decimalLatitude")) # Convert the occurence dataset into a sf object to transform the coordinate system
st_crs(skunks) <- st_crs("+proj=longlat +datum=WGS84") # Set the original coordinate system for the sf object 
skunks <- st_transform(skunks, st_crs("+proj=aea +lat_0=45 +lon_0=-126 +lat_1=50 +lat_2=58.5 +x_0=1000000 +y_0=0 +datum=NAD83 +units=m +no_defs")) # Convert it to the new system 
coords <- st_coordinates(skunks) # Gather the new longitude and latitude data
skunks <- cbind(skunks, coords) # Join the longitude and latitude back to the dataset 
```

```{r}
window <- as.owin(DATA$Window)
ppp_skunks <- ppp(x = skunks$X, y = skunks$Y, window = window) # Obtain a ppp object with the coordinate and window data 
```

```{r}
plot(ppp_skunks,
     cols = 4,
     pch = 16,
     main = "Skunks point data in BC")
```

